# If there are words that you think should not be treated as typo.
# Please list here along with a comment.
[default.extend-words]
"ponter" = "ponter"
"pont" = "pont"
"fre" = "fre"
"poiinter" = "poiinter"
"fromi" = "fromi"
"toi" = "toi"

[files]
