name: Rust

on:
  push:
    branches: [ "master","leetcode-*"  ]
  pull_request:
    branches: [ "master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Check workflow permissions
      id: check_permissions
      uses: scherermichael-oss/action-has-permission@1.0.6
      with:
        required-permission: write
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Run clippy action to produce annotations
      uses: actions-rs/clippy-check@v1
      if: steps.check_permissions.outputs.has-permission
      with:
        args: --all-features -- -D warnings
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Run clippy manually without annotations
      if: ${{ !steps.check_permissions.outputs.has-permission }}
      run: cargo clippy --all-features -- -D warnings

